name: CI - Flask Docker App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Installer Python pour tester/linter
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3. Installer dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      # 4. Vérifier le style du code
      - name: Run Linter
        run: flake8 .

      # 5. Construire l'image Docker
      - name: Build Docker image
        run: docker build -t devsecure-api .

      # 6. Lancer le conteneur en arrière-plan
      - name: Run container
        run: docker run -d -p 3000:3000 --name flask_app devsecure-api

      # 7. Attendre que l'app démarre
      - name: Wait for container
        run: sleep 5

      # 8. Tester si l'app répond
      - name: Test app response
        run: curl --fail http://localhost:3000/ | grep "Hello from Flask!"

      # 9. Nettoyer
      - name: Stop and remove container
        if: always()
        run: |
          docker stop flask_app || true
          docker rm flask_app || true